---
title: The Covariance of Covariances
author: 
    - name: Jan de Leeuw
      orcid: 0000-0003-1420-1797
      email: jan@deleeuwpdx.net
      affiliation: 
        - name: University of California Los Angeles
          city: Los Angeles
          state: CA
          url: www.ucla.edu
      license: "CC0"
date: last-modified
date-format: long
bibliography: [mypubs.bib, total.bib]
number-sections: true
pdf-engine: lualatex
keep-tex: true
format:
   pdf:
    fontsize: 12pt
    include-in-header: 
     - preamble.tex
    keep-tex: true
    link-citations: true
    documentclass: scrartcl
    number-sections: true
   html:
    fontsize: 12pt
    include-in-header: 
     - preamble.css
    keep-md: true
    number-sections: true
toc: true
toc-depth: 3
editor: source
papersize: letter
graphics: true
link-citations: true
mainfont: Times New Roman
abstract: TBD
---

```{r loadpackages, echo = FALSE}
suppressPackageStartupMessages(library(knitr, quietly = TRUE))
suppressPackageStartupMessages(library(tinytex, quietly = TRUE))
```

\sectionbreak 

**Note:** This is a working manuscript which will be expanded/updated
frequently. All suggestions for improvement are welcome. All Rmd, tex,
html, pdf, R, and C files are in the public domain. Attribution will be
appreciated, but is not required. The files can be found at
<https://github.com/deleeuw> 

\sectionbreak

# Introduction

Discrete, continuous. @holland_79, @gifi_B_90


Suppose we have $p$ real vectors $x_1,\cdots,x_p$ of length $m$, which we call *profiles*. The profiles can be
collected in the rows of a $p\times m$ *profile matrix* $X$. 

Define a random vector $\ul{e}$, which takes as its values the $n$ unit vectors $e_1,\cdots,e_n$. Unit vector
$e_r$ has all its elements equal to zero, except for element $r$, which is equal to one. 
Define $\pi_r:=\text{prob}(\ul{e}=e_r)$. We use the "Dutch Convention" of underlining random variables (@hemelrijk_66). The symbol $:=$ is used for definitions.


Next define the raw product moments, or moments about zero, of order one as
$$
\mu_i:=\sum_{r=1}^p \pi_rx_{ri},
$$
of order two as
$$
\mu_{ij}=\sum_{r=1}^p \pi_rx_{ri}x_{rj},
$$
of order three as
$$
\mu_{ijk}=\sum_{r=1}^p \pi_rx_{ri}x_{rj}x_{rk},
$$
and so on. Note that we can have
$$
\mu_{iii}=\sum_{r=1}^p \pi_rx_{ri}^3\\
\mu_{iij}=\sum_{r=1}^p \pi_rx_{ri}^2x_{rj}
$$
which are sometimes written as $\mu_i^3$ and $\mu_{ij}^{21}$.


Next, suppose we have $n$ independent copies  $\ul{e}_1,\cdots\ul{e}_n$ of $\ul{e}$ . 
Suppose $$\ul{p}=\frac{1}{n}\sum_{\nu=1}^n\ul{e}_\nu$$ is the vector of $N$ observed relative
\smash{frequency} of profile $\nu$. 
\smash{Define\footnote{}} the covariance of variables $i$ and $j$ as
$$
\ul{c}_{ij}:=\sum_\nu \ul{p}_\nu x_{\nu i}x_{\nu j}-\sum_\nu \ul{p}_\nu x_{\nu i}\sum_\eta\ul{p}_\eta x_{\eta j}
$$
We want to compute the expected value of the covariances $\ul{c}_{ij}$ and the covariance of pairs of
covariances $\ul{c}_{ij}$ and $\ul{c}_{kl}$. 

## Computation

Let $\ul{\epsilon}_v:=\ul{p}_v-\pi_v$ so that 
$$
\mathcal{E}(\ul{\epsilon}_\nu)=0,
$$ 
and 
$$
\mathcal{E}(\ul{\epsilon}_\nu\ul{\epsilon}_\eta)=n^{-1}(\delta^{\nu\eta}\pi_\nu-\pi_\nu\pi_\eta).
$$

Now we can write
$$
\ul{c}_{ij}=\gamma_{ij}+\sum_\nu \ul{\epsilon}_\nu(x_{\nu i}-\mu_i)(x_{\nu j}-\mu_j)
-\sum_\nu\sum_\eta\ul{\epsilon}_\nu\ul{\epsilon}_\eta(x_{\nu i}-\mu_i)(x_{\eta j}-\mu_j),
$$
with
$$
\gamma_{ij}=\sum_\nu\pi_\nu(x_{\nu i}-\mu_i)(x_{\nu j}-\mu_j).
$$
and 
$$
\mu_i=\sum_\nu \pi_\nu x_{\nu i}
$$

It follows that
$$
\mathcal{E}(\ul{c}_{ij})=\gamma_{ij}-\frac{1}{n}\sum_\nu\sum_\eta x_{\nu i}x_{\eta j}(\delta^{\nu\eta}\pi_\nu-\pi_\nu\pi_\eta)=\frac{n-1}{n}\gamma_{ij}.
$$
Next, define
$$
\ul{\delta}_{ij}:=\ul{c}_{ij}-\frac{n-1}{n}\gamma_{ij}.
$$
The $\ul{\delta}_{ij}$ have expectation zero, and
$$
\text{COV}(\ul{c}_{ij},\ul{c}_{kl})=\mathcal{E}(\ul{\delta}_{ij}\ul{\delta}_{kl}).
$$
We have
\begin{subequations}
\begin{align}
\ul{\delta}_{ij}&=\frac{1}{n}\gamma_{ij}+\sum_\nu\ul{\epsilon}_\nu\{x_{\nu i}x_{\nu j}
-\mu_jx_{\nu i}-\mu_ix_{\nu j}\}
-\sum_\nu\sum_\eta\ul{\epsilon}_\nu\ul{\epsilon}_\eta x_{\nu i}x_{\eta j},\label{eq-expd1}\\
\ul{\delta}_{kl}&=\frac{1}{n}\gamma_{kl}+\sum_\nu\ul{\epsilon}_\nu\{x_{\nu k}x_{\nu l}
-\mu_lx_{\nu k}-\mu_kx_{\nu l}\}
-\sum_\nu\sum_\eta\ul{\epsilon}_\nu\ul{\epsilon}_\eta x_{\nu k}x_{\eta l}.\label{eq-expd2}
\end{align}
\end{subequations}

## Asymptotics

From

$$
\mathcal{E}(\ul{\delta}_{ij}\ul{\delta}_{kl})=\frac{1}{n}\sum_\nu\sum_\eta(\delta^{\nu\eta}\pi_\nu-\pi_\nu\pi_\eta)
\{x_{\nu i}x_{\nu j}
-\mu_jx_{\nu i}-\mu_ix_{\nu j}\}\{x_{\eta k}x_{\eta l}
-\mu_lx_{\eta k}-\mu_kx_{\eta l}\}=\frac{1}{n}\mu_{ijkl}-
$$
$$
x_{\nu i}x_{\nu j}=(x_{\nu i}-\mu_i)(x_{\nu j}-\mu_j)+x_{\nu i}\mu_j+x_{\nu j}\mu_i-\mu_i\mu_j
$$
$$x_{\nu i}x_{\nu j}
-\mu_jx_{\nu i}-\mu_ix_{\nu j}=(x_{\nu i}-\mu_i)(x_{\nu j}-\mu_j)-\mu_i\mu_j
$$
$$
\mathcal{E}(\ul{\delta}_{ij}\ul{\delta}_{kl})=\frac{1}{n}\sum_\nu\sum_\eta(\delta^{\nu\eta}\pi_\nu-\pi_\nu\pi_\eta)
\{(x_{\nu i}-\mu_i)(x_{\nu j}-\mu_j)-\mu_i\mu_j\}\{(x_{\eta k}-\mu_k)(x_{\eta l}-\mu_l)-\mu_k\mu_l\}=\\
\sigma_{ijkl}-\mu_k\mu_l\sigma_{ij}-\mu_i\mu_j\sigma_{kl}+\mu_i\mu_j\mu_k\mu_l-(\sigma_{ij}-\mu_i\mu_j)(\sigma_{kl}-\mu_k\mu_l)=\sigma_{ijkl}-\sigma_{ij}\sigma_{kl}
$$

## Exact Calculations

If we multiply \eqref{eq-expd1} and \eqref{eq-expd2} we have nine terms. Taking expectations of each of these nine terms gives
$$
\text{term I}:\frac{1}{n^2}\gamma_{ij}\gamma_{kl}
$$
$$
\text{term II}:\frac{1}{n}\gamma_{ij}\mathcal{E}(\sum_\nu\ul{\epsilon}_\nu\{x_{\nu k}x_{\nu l}
-\mu_lx_{\nu k}-\mu_kx_{\nu l}\})=0
$$
$$
\text{term III}:-\frac{1}{n}\gamma_{ij}\mathcal{E}(\sum_\nu\sum_\eta\ul{\epsilon}_\nu\ul{\epsilon}_\eta x_{\nu k}x_{\eta l})=-\frac{1}{n^2}\gamma_{ij}\gamma_{kl}
$$
$$
\text{term IV}:\frac{1}{n}\gamma_{kl}\mathcal{E}(\sum_\nu\ul{\epsilon}_\nu\{x_{\nu i}x_{\nu j}
-\mu_jx_{\nu i}-\mu_ix_{\nu j}\})=0
$$
$$
\text{term V}:\frac{1}{n}\sum_\nu\sum_\eta(\delta^{\nu\eta}\pi_\nu-\pi_\nu\pi_\eta)\{x_{\nu i}x_{\nu j}
-\mu_jx_{\nu i}-\mu_ix_{\nu j}\}\{x_{\eta k}x_{\eta l}
-\mu_lx_{\eta k}-\mu_kx_{\eta l}\}
$$

$$
\text{term VI}:-\sum_\alpha\sum_\nu\sum_\eta\mathcal{E}(\ul{\epsilon}_\alpha\ul{\epsilon}_\nu\ul{\epsilon}_\eta)\{x_{\alpha i}x_{\alpha j}
-\mu_jx_{\alpha i}-\mu_ix_{\alpha j}\} x_{\nu k}x_{\eta l}
$$

$$
\text{term VII}:-\frac{1}{n}\gamma_{kl}\sum_\nu\sum_\eta\mathcal{E}(\ul{\epsilon}_\nu\ul{\epsilon}_\eta) x_{\nu i}x_{\eta j}=-\frac{1}{n^2}\gamma_{ij}\gamma_{kl}
$$
$$
\text{term VIII}:-\sum_\nu\sum_\eta\sum_\alpha\mathcal{E}(\ul{\epsilon}_\nu\ul{\epsilon}_\eta\ul{\epsilon}_\alpha)x_{\nu i}x_{\eta j}\{x_{\alpha k}x_{\alpha l}
-\mu_lx_{\alpha k}-\mu_kx_{\alpha l}\}
$$

$$
\text{term IX}:\sum_\nu\sum_\eta\sum_\alpha\sum_\beta\mathcal{E}(\ul{\epsilon}_\nu\ul{\epsilon}_\eta\ul{\epsilon}_\alpha\ul{\epsilon}_\beta) x_{\nu i}x_{\eta j}x_{\alpha k}x_{\beta l}
$$

